### ISSUE TITLE
server crashes when teleporting to your skyblock island

### ISSUE THREAD

**Issue by SuccBT** [tyap-lyap/skylands#14]
when i do the command /sl home my server freezes and crashes

this is the crash log [HVGuyGVUHVuyVYvUTYCYTviuty99.txt](https://github.com/tyap-lyap/skylands/files/13805405/HVGuyGVUHVuyVYvUTYCYTviuty99.txt)

let me know if you need anymore informatiob

**Comment by PinkGoosik** [comment]
Id like to know what version of minecraft and the mod are you using and what mods you have beside skylands

**Comment by SuccBT** [comment]
hi sorry for slow response

**Comment by SuccBT** [comment]
> Id like to know what version of minecraft and the mod are you using and what mods you have beside skylands

hi sorry for slow response 

i'm using fabric 1.20.1 with the following mods on my server

all the trims
alternate current
amethyst gravity reattracted
architectury
automobility
autotag
blockus
blossom homes
blossom lib
blossom tpa
brewin and chewin
cardinal components
cloth config
clumps fabric
collective
create
create structures
diggusmaximus
easyauth
exposure
fabric api
fabric end remastered
fabric language koltin
farmers delight
fastload+
ferritecore
forgeconfigapiport
getittoigetherdrops
gravity changer
i am music player
immersive aircraft
immersive paintings
invview
justmobheads
justplayerheads
krypton
leavesbegone
ledger
lightmanscurrency
luckperms
mc2discord
medieval origins
memoryleakfix
modmenu
moonlight
origins
otyacraftengine
pehkui
puzzleslib
servercore
simplehats
skin restorer
spark
starlight
supplementaries
tntbreaksbedrock
toms storage
travelers backpack
trinkets
very many players
yungs api
yungs better end islands
yungs better jungle temples
yungs mineshafts
yungs nether fortress
yungs better strongholds
