### ISSUE TITLE
[question] Can I add to existing Server?

### ISSUE THREAD

**Issue by Merith-TK** [tyap-lyap/skylands#5]
So the question is, I have an Anarchy SMP, and I want players to be able to just warp to a isolated area, like an skyblock where they can take time and relax, maybe even setup an small hidden base there with their items

is this possible with this mod?

**Comment by PinkGoosik** [comment]
Yes

**Comment by SuperErnD** [comment]
i think yes, but it fabric, so if u use a spigot use instead IridiumSkyblock

**Comment by Merith-TK** [comment]
its a fabric modpack, so I should be fine in that regard

**Comment by SuperErnD** [comment]
@PinkGoosik close it

**Comment by PinkGoosik** [comment]
join us on discord if you'd like to discuss skylands
