### ISSUE TITLE
Can't skip the night on island

### ISSUE THREAD

**Issue by LeD0c4** [tyap-lyap/skylands#7]
Hi, i would like to know if i'm the only one who can't skip the night when i'm on player island, but i can skip the night on hub

**Comment by PinkGoosik** [comment]
Islands comply vanilla behaviour, i.e. everyone on a server should sleep to skip the night, if you're alone on a server and still can't skip then I don't know what's wrong

**Comment by LeD0c4** [comment]
thks for the reply. some mods have some curious behavior
